### ISSUE TITLE
[전체] 메인 시안

### ISSUE THREAD

**Issue by freckie** [KHU-Dasom/Dasom-Website#1]
## 메인 시안
- 홈페이지 메인 부분의 디자인 결정하기
- 작성은 다음 예시를 참고해주세요.

**Comment by freckie** [comment]
## 예시) 메인시안 - 1
![image](https://colorlib.com/wp/wp-content/uploads/sites/2/philosophy-free-lifestyle-blog-website-template.jpg)

* 위 시안에서 상단 색상은 파란색으로 변경하면 좋을 것 같습니다. (색상코드 : #FFE632)
* 상단 좌측 소셜 아이콘은 불필요해서 제거하면 좋을 것 같습니다.
* 각 버튼 별로 클릭했을 때 링크되어야 할 페이지는 추가로 따로 아래 코멘트에 정의해두겠습니다.
* 참고 링크 : []()

**Comment by earthssu** [comment]
### 타임라인 시안
![구성예시2](https://user-images.githubusercontent.com/39795055/55963465-dc803c80-5cad-11e9-83e1-dfde3c080747.jpg)

- 메인페이지에 들어갈 타임라인 시안입니다.

- 시안과 같이 가로줄에 시간에 따라 동그라미 그려넣고, 동그라미 위에 마우스 갖다대거나 클릭하면 말풍선처럼 띄워지면서 사진과 코멘트가 적혀있었으면 좋겠습니다. 

- 한페이지로 부족한 경우, 양옆에 화살표를 넣어 화살표를 클릭하면 슬라이드처럼 옆으로 넘어가는 형식이면 좋겠습니다.

**Comment by earthssu** [comment]
### 메인페이지 시안
![메인예시2](https://user-images.githubusercontent.com/39795055/55965658-fc196400-5cb1-11e9-959c-baf2f2d68910.jpg)

- [데모 링크](https://colorlib.com/pixova-lite/), [다운로드 링크](https://colorlib.com/wp/themes/pixova-lite/)

- 메인 가장 첫번째 페이지는 첫번째 이미지와 같이 사진 또는 영상으로 채워진 배경이 있고, 왼쪽 상단에 메뉴 표시가 있었으면 합니다. 혹시나 배경을 풀로 채우는 것이 부담스러워 보이거나 어색할 경우, 위아래 여백을 약간 준 뒤에 여백은 흰색으로 두고, 그 여백에다 메뉴 아이콘을 넣었으면 좋겠습니다. 메뉴 아이콘은 다솜 로고로, 진한 핑크색이 어울릴 듯합니다.

- 다솜 소개 페이지는 위에서 세번째 이미지와 같이 이미지를 나열하고 밑에 간단한 코멘트를 다는 형식이었으면 합니다. 다만 사진 사이의 간격은 좀 띄우고, 마우스를 올리면 그 글이 부각되는 것과 같은 효과가 들어갔으면 좋겠습니다.

- 전체적인 톤은 밝은색이었으면 하고, 포인트색은 진한 핑크였으면 좋겠습니다. 다 파스텔톤이면 축 처지는 느낌이고 자칫하면 촌스러울 것 같아서... 배경이 너무 흰색이면 밋밋할 것 같아 연한 올리브톤이나 귤색이랑 섞으면 잘어울릴 것 같습니다.

![색상예시4](https://user-images.githubusercontent.com/39795055/55965667-00458180-5cb2-11e9-876d-77f02e52ebb0.png)
![색상예시5](https://user-images.githubusercontent.com/39795055/55965670-00458180-5cb2-11e9-82d6-518da5460935.png)

**Comment by devSoyoung** [comment]
@earthssu 위 색 조합 너무 예쁘네요! 
핑크색 포인트 좋은 것 같아요. 저대로 색조합 가도 괜찮을 것 같습니다 :) 
저는 찬성 한 표!

**Comment by freckie** [comment]
@earthssu 
색을 잘 정해서 색에 이름을 붙였으면 좋겠어요.
예를 들어 사랑을 뜻하는 다솜 핑크라던가, 술을 뜻하는 다솜 그린 이라던가 ㅎㅎ
