### ISSUE TITLE
[디자인] 로그인 페이지 구현한 것 공유

### ISSUE THREAD

**Issue by devSoyoung** [KHU-Dasom/Dasom-Website#4]
토이프로젝트로 만들었던 슬라이드 형식 로그인, 회원가입 페이지 공유드립니다.
반응이 괜찮을 경우 다솜 홈페이지에 적용하면 좋을 것 같아요

* [슬라이드 형식 로그인 페이지 링크](https://github.com/devSoyoung/react-sign-up-slide)

**Comment by freckie** [comment]
@devSoyoung 
다솜 컬러를 설정해서 보여주신 로그인 페이지의 메인 컬러로 적용하면 좋을 것 같습니다.

모바일 화면에서는 어떻게 나오는지 보고 싶은데, 데모 사이트는 없나요?

**Comment by devSoyoung** [comment]
@freckie 
모바일 대응해서 만든 페이지는 아니라 아마 모바일에서는 많이 깨질 것 같습니다.
주말에 수정해서 다시 공유해드릴게요.
