### ISSUE TITLE
[프론트엔드] 웹사이트 템플릿 선정

### ISSUE THREAD

**Issue by devSoyoung** [KHU-Dasom/Dasom-Website#5]
## 웹사이트 템플릿 선정
활용하면 좋을 것 같은 템플릿 이미지, 링크 남겨주세요 :)

**Comment by earthssu** [comment]
![digilab-free-template](https://user-images.githubusercontent.com/39795055/56105917-a1199280-5f79-11e9-96f3-cbb6b295c608.jpg)

[데모 링크](https://colorlib.com/preview/#digilab), [다운로드 링크](https://colorlib.com/wp/template/digilab/)

- 전체적인 구성이 깔끔하고, 우리가 현재 필요로 하는 페이지 구성에서 활용하면 좋은 것들이 많아 링크 남깁니다!

- 사진 띄워놓고 옆으로 넘기는 방식은 다솜 소개하는 공간 등에 활용하면 좋을 것  같습니다.

**Comment by devSoyoung** [comment]
@earthssu 좋네요! 아, 모바일도 가능한 반응형 사이트이면 좋을 것 같아욥

**Comment by devSoyoung** [comment]
![image](https://user-images.githubusercontent.com/42922453/56110080-1beca880-5f8e-11e9-9103-1ca6a867bf14.png)

예쁘고 좋은데, 유료네요.
* [링크](https://flatlogic.com/admin-dashboards/sing-app-html5?ref=zfHq8xuAaw)

**Comment by devSoyoung** [comment]
![image](https://user-images.githubusercontent.com/42922453/56110155-6bcb6f80-5f8e-11e9-9ab6-03037f2eabbe.png)

* [링크](https://www.wrappixel.com/templates/ample-admin-lite/)

**Comment by devSoyoung** [comment]
![image](https://user-images.githubusercontent.com/42922453/56110206-93bad300-5f8e-11e9-9abc-c88157e77957.png)

* [링크](https://github.com/puikinsh/Adminator-admin-dashboard)

**Comment by freckie** [comment]
## 메인 페이지 템플릿

![Image](https://colorlib.com/wp/wp-content/uploads/sites/2/webuni-free-template.jpg)

[데모 링크](https://colorlib.com/preview/#webuni), [다운로드 링크](https://colorlib.com/wp/template/webuni/)

메인 페이지에 활용하면 좋을 것 같습니다.
주로 검은 배경에 핑크~빨강 사이의 색으로 포인트를 줬는데, 이 디자인 또한 참고했으면 좋겠습니다.

두 번째 섹션인 Out Categories 는 우리 동아리 활동 사진 등으로 채우면 좋을 것 같구요,
4번째 섹션인 Featured Courses를 아예 지우고 타임라인 등으로 대체했으면 좋겠습니다.

**Comment by DevLeti** [comment]
![image](https://user-images.githubusercontent.com/25370441/56279903-fd301280-6143-11e9-9957-cbd8998ef291.png)
![image](https://user-images.githubusercontent.com/25370441/56279934-12a53c80-6144-11e9-9dac-9643776b0b48.png)
[데모 링크](https://bootstrapmade.com/demo/themes/Regna/) [다운로드 링크](https://bootstrapmade.com/regna-bootstrap-onepage-template/#download)

- 홈페이지를 들어갔을때 보이는 화면이 심플해 캐치프레이즈가 한눈에 잘 들어옵니다.
- 페이지를 내리면서 나오는 효과, 메뉴들에 마우스를 올렸을때 나오는 효과 등이 이미 구현되어있습니다.
- 부트스트랩 테마이기 때문에 모바일또한 호환됩니다.

**Comment by freckie** [comment]
@DevLeti 
이게 제일 깔끔하고 활용하기 쉬울 것 같습니다.
전 메인 템플릿 이거로 채택했음 좋겠습니다
